[2024-05-25T16:46:13.505+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-25T16:46:13.522+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_spotify_dag.create_table_task manual__2024-05-25T16:46:11.145718+00:00 [queued]>
[2024-05-25T16:46:13.528+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_spotify_dag.create_table_task manual__2024-05-25T16:46:11.145718+00:00 [queued]>
[2024-05-25T16:46:13.528+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-25T16:46:13.539+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table_task> on 2024-05-25 16:46:11.145718+00:00
[2024-05-25T16:46:13.551+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=158) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-25T16:46:13.552+0000] {standard_task_runner.py:63} INFO - Started process 160 to run task
[2024-05-25T16:46:13.552+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_spotify_dag', 'create_table_task', 'manual__2024-05-25T16:46:11.145718+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/spotify_dag.py', '--cfg-path', '/tmp/tmpni6_qyax']
[2024-05-25T16:46:13.554+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask create_table_task
[2024-05-25T16:46:13.592+0000] {task_command.py:426} INFO - Running <TaskInstance: my_spotify_dag.create_table_task manual__2024-05-25T16:46:11.145718+00:00 [running]> on host 146d694e16a6
[2024-05-25T16:46:13.659+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kaz' AIRFLOW_CTX_DAG_ID='my_spotify_dag' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-25T16:46:11.145718+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-25T16:46:11.145718+00:00'
[2024-05-25T16:46:13.661+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-25T16:46:13.671+0000] {sql.py:276} INFO - Executing: 
                create table if not exists my_listened_song(
                    song_name varchar(50),
                    artis_name varchar(50),
                    album_name varchar(50),
                    release varchar(10),
                    played_at datetime,
                    CONSTRAINT primary_key_constraint PRIMARY KEY (played_at)
                )
                
[2024-05-25T16:46:13.680+0000] {base.py:84} INFO - Using connection ID 'postgre_spotify_sql' for task execution.
[2024-05-25T16:46:13.687+0000] {base.py:84} INFO - Using connection ID 'postgre_spotify_sql' for task execution.
[2024-05-25T16:46:13.722+0000] {sql.py:470} INFO - Running statement: 
                create table if not exists my_listened_song(
                    song_name varchar(50),
                    artis_name varchar(50),
                    album_name varchar(50),
                    release varchar(10),
                    played_at datetime,
                    CONSTRAINT primary_key_constraint PRIMARY KEY (played_at)
                )
                , parameters: None
[2024-05-25T16:46:13.737+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-25T16:46:13.738+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 418, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 475, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedObject: type "datetime" does not exist
LINE 7:                     played_at datetime,
                                      ^

[2024-05-25T16:46:13.748+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=my_spotify_dag, task_id=create_table_task, run_id=manual__2024-05-25T16:46:11.145718+00:00, execution_date=20240525T164611, start_date=20240525T164613, end_date=20240525T164613
[2024-05-25T16:46:13.760+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task create_table_task (type "datetime" does not exist
LINE 7:                     played_at datetime,
                                      ^
; 160)
[2024-05-25T16:46:13.806+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-25T16:46:13.837+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
